version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - errname
    - errorlint
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
    - unparam
  disable:
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G104 # Audit errors not checked (we use blank identifier)
      - G301 # Directory permissions (0755 is acceptable for user cache)
      - G304 # File path from variable (for user cache directory)
      - G306 # File permissions (0644 is acceptable for cache files)
      - G404 # Weak random for jitter (not security-critical)
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - vendor
    - .git

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/amjadjibon/gotick
