// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: pricing.proto

package yfinance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PricingData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price             float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Time              int64                  `protobuf:"zigzag64,3,opt,name=time,proto3" json:"time,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Exchange          string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	QuoteType         int32                  `protobuf:"varint,6,opt,name=quote_type,json=quoteType,proto3" json:"quote_type,omitempty"`
	MarketHours       int32                  `protobuf:"varint,7,opt,name=market_hours,json=marketHours,proto3" json:"market_hours,omitempty"`
	ChangePercent     float32                `protobuf:"fixed32,8,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	DayVolume         int64                  `protobuf:"zigzag64,9,opt,name=day_volume,json=dayVolume,proto3" json:"day_volume,omitempty"`
	DayHigh           float32                `protobuf:"fixed32,10,opt,name=day_high,json=dayHigh,proto3" json:"day_high,omitempty"`
	DayLow            float32                `protobuf:"fixed32,11,opt,name=day_low,json=dayLow,proto3" json:"day_low,omitempty"`
	Change            float32                `protobuf:"fixed32,12,opt,name=change,proto3" json:"change,omitempty"`
	ShortName         string                 `protobuf:"bytes,13,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	ExpireDate        int64                  `protobuf:"zigzag64,14,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	OpenPrice         float32                `protobuf:"fixed32,15,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	PreviousClose     float32                `protobuf:"fixed32,16,opt,name=previous_close,json=previousClose,proto3" json:"previous_close,omitempty"`
	StrikePrice       float32                `protobuf:"fixed32,17,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	UnderlyingSymbol  string                 `protobuf:"bytes,18,opt,name=underlying_symbol,json=underlyingSymbol,proto3" json:"underlying_symbol,omitempty"`
	OpenInterest      int64                  `protobuf:"zigzag64,19,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	OptionsType       int64                  `protobuf:"zigzag64,20,opt,name=options_type,json=optionsType,proto3" json:"options_type,omitempty"`
	MiniOption        int64                  `protobuf:"zigzag64,21,opt,name=mini_option,json=miniOption,proto3" json:"mini_option,omitempty"`
	LastSize          int64                  `protobuf:"zigzag64,22,opt,name=last_size,json=lastSize,proto3" json:"last_size,omitempty"`
	Bid               float32                `protobuf:"fixed32,23,opt,name=bid,proto3" json:"bid,omitempty"`
	BidSize           int64                  `protobuf:"zigzag64,24,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	Ask               float32                `protobuf:"fixed32,25,opt,name=ask,proto3" json:"ask,omitempty"`
	AskSize           int64                  `protobuf:"zigzag64,26,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	PriceHint         int64                  `protobuf:"zigzag64,27,opt,name=price_hint,json=priceHint,proto3" json:"price_hint,omitempty"`
	Vol_24Hr          int64                  `protobuf:"zigzag64,28,opt,name=vol_24hr,json=vol24hr,proto3" json:"vol_24hr,omitempty"`
	VolAllCurrencies  int64                  `protobuf:"zigzag64,29,opt,name=vol_all_currencies,json=volAllCurrencies,proto3" json:"vol_all_currencies,omitempty"`
	FromCurrency      string                 `protobuf:"bytes,30,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	LastMarket        string                 `protobuf:"bytes,31,opt,name=last_market,json=lastMarket,proto3" json:"last_market,omitempty"`
	CirculatingSupply float64                `protobuf:"fixed64,32,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	MarketCap         float64                `protobuf:"fixed64,33,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PricingData) Reset() {
	*x = PricingData{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingData) ProtoMessage() {}

func (x *PricingData) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingData.ProtoReflect.Descriptor instead.
func (*PricingData) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *PricingData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PricingData) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PricingData) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PricingData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PricingData) GetQuoteType() int32 {
	if x != nil {
		return x.QuoteType
	}
	return 0
}

func (x *PricingData) GetMarketHours() int32 {
	if x != nil {
		return x.MarketHours
	}
	return 0
}

func (x *PricingData) GetChangePercent() float32 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *PricingData) GetDayVolume() int64 {
	if x != nil {
		return x.DayVolume
	}
	return 0
}

func (x *PricingData) GetDayHigh() float32 {
	if x != nil {
		return x.DayHigh
	}
	return 0
}

func (x *PricingData) GetDayLow() float32 {
	if x != nil {
		return x.DayLow
	}
	return 0
}

func (x *PricingData) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *PricingData) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *PricingData) GetExpireDate() int64 {
	if x != nil {
		return x.ExpireDate
	}
	return 0
}

func (x *PricingData) GetOpenPrice() float32 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *PricingData) GetPreviousClose() float32 {
	if x != nil {
		return x.PreviousClose
	}
	return 0
}

func (x *PricingData) GetStrikePrice() float32 {
	if x != nil {
		return x.StrikePrice
	}
	return 0
}

func (x *PricingData) GetUnderlyingSymbol() string {
	if x != nil {
		return x.UnderlyingSymbol
	}
	return ""
}

func (x *PricingData) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *PricingData) GetOptionsType() int64 {
	if x != nil {
		return x.OptionsType
	}
	return 0
}

func (x *PricingData) GetMiniOption() int64 {
	if x != nil {
		return x.MiniOption
	}
	return 0
}

func (x *PricingData) GetLastSize() int64 {
	if x != nil {
		return x.LastSize
	}
	return 0
}

func (x *PricingData) GetBid() float32 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *PricingData) GetBidSize() int64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

func (x *PricingData) GetAsk() float32 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *PricingData) GetAskSize() int64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

func (x *PricingData) GetPriceHint() int64 {
	if x != nil {
		return x.PriceHint
	}
	return 0
}

func (x *PricingData) GetVol_24Hr() int64 {
	if x != nil {
		return x.Vol_24Hr
	}
	return 0
}

func (x *PricingData) GetVolAllCurrencies() int64 {
	if x != nil {
		return x.VolAllCurrencies
	}
	return 0
}

func (x *PricingData) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *PricingData) GetLastMarket() string {
	if x != nil {
		return x.LastMarket
	}
	return ""
}

func (x *PricingData) GetCirculatingSupply() float64 {
	if x != nil {
		return x.CirculatingSupply
	}
	return 0
}

func (x *PricingData) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\"\x85\b\n" +
	"\vPricingData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x12R\x04time\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12\x1d\n" +
	"\n" +
	"quote_type\x18\x06 \x01(\x05R\tquoteType\x12!\n" +
	"\fmarket_hours\x18\a \x01(\x05R\vmarketHours\x12%\n" +
	"\x0echange_percent\x18\b \x01(\x02R\rchangePercent\x12\x1d\n" +
	"\n" +
	"day_volume\x18\t \x01(\x12R\tdayVolume\x12\x19\n" +
	"\bday_high\x18\n" +
	" \x01(\x02R\adayHigh\x12\x17\n" +
	"\aday_low\x18\v \x01(\x02R\x06dayLow\x12\x16\n" +
	"\x06change\x18\f \x01(\x02R\x06change\x12\x1d\n" +
	"\n" +
	"short_name\x18\r \x01(\tR\tshortName\x12\x1f\n" +
	"\vexpire_date\x18\x0e \x01(\x12R\n" +
	"expireDate\x12\x1d\n" +
	"\n" +
	"open_price\x18\x0f \x01(\x02R\topenPrice\x12%\n" +
	"\x0eprevious_close\x18\x10 \x01(\x02R\rpreviousClose\x12!\n" +
	"\fstrike_price\x18\x11 \x01(\x02R\vstrikePrice\x12+\n" +
	"\x11underlying_symbol\x18\x12 \x01(\tR\x10underlyingSymbol\x12#\n" +
	"\ropen_interest\x18\x13 \x01(\x12R\fopenInterest\x12!\n" +
	"\foptions_type\x18\x14 \x01(\x12R\voptionsType\x12\x1f\n" +
	"\vmini_option\x18\x15 \x01(\x12R\n" +
	"miniOption\x12\x1b\n" +
	"\tlast_size\x18\x16 \x01(\x12R\blastSize\x12\x10\n" +
	"\x03bid\x18\x17 \x01(\x02R\x03bid\x12\x19\n" +
	"\bbid_size\x18\x18 \x01(\x12R\abidSize\x12\x10\n" +
	"\x03ask\x18\x19 \x01(\x02R\x03ask\x12\x19\n" +
	"\bask_size\x18\x1a \x01(\x12R\aaskSize\x12\x1d\n" +
	"\n" +
	"price_hint\x18\x1b \x01(\x12R\tpriceHint\x12\x19\n" +
	"\bvol_24hr\x18\x1c \x01(\x12R\avol24hr\x12,\n" +
	"\x12vol_all_currencies\x18\x1d \x01(\x12R\x10volAllCurrencies\x12#\n" +
	"\rfrom_currency\x18\x1e \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vlast_market\x18\x1f \x01(\tR\n" +
	"lastMarket\x12-\n" +
	"\x12circulating_supply\x18  \x01(\x01R\x11circulatingSupply\x12\x1d\n" +
	"\n" +
	"market_cap\x18! \x01(\x01R\tmarketCapB+Z)github.com/amjadjibon/gotick/pkg/yfinanceb\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pricing_proto_goTypes = []any{
	(*PricingData)(nil), // 0: PricingData
}
var file_pricing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
